version: '3.8'

services:
  frontend:
    build: ./frontend
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      - MONGODB_URI=mongodb://database:27017/db
    networks:
      - app-network

  database:
    image: mongo:jammy@sha256:d0e90b851330d0e8e3c17767d1f3152c452ed549cf0c61d80c945cc883c1ce79
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:perl@sha256:14902c0c0ebafd48155b126693dfc551e4d11596f1bacfbe309d39365e92aced
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local